name: Dump
on: push
jobs:
    debug:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/action.yml
              id: dump
              with:
                enable-context: 'true'
            - run: echo "${DATE}"
              env:
                DATE: ${{ steps.dump.outputs.deumped-date }}