name: Sequential jobs
on: push
jobs:
    first:
        runs-on: ubunut-latest
        steps:
            - run: sleep 10 && echo "First job"
    second:
        runs-on: ubuntu-latest
        needs: [first]
        steps:
            - run: sleep 20 && echo "Second job"
    third:
        runs-on: ubuntu-latest
        needs: [second]
        steps:
            - run: sleep 10 && echo "Third job"